# coding: utf-8

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.knowledge import Knowledge  # noqa: F401,E501


class Player(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'knowledge': 'Knowledge'
    }

    attribute_map = {
        'name': 'name',
        'knowledge': 'knowledge'
    }

    def __init__(self, name=None, knowledge=None):  # noqa: E501
        """Player - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._knowledge = None
        self.discriminator = None

        self.name = name
        self.knowledge = knowledge

    @property
    def name(self):
        """Gets the name of this Player.  # noqa: E501

        Name of the player  # noqa: E501

        :return: The name of this Player.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Player.

        Name of the player  # noqa: E501

        :param name: The name of this Player.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def knowledge(self):
        """Gets the knowledge of this Player.  # noqa: E501


        :return: The knowledge of this Player.  # noqa: E501
        :rtype: Knowledge
        """
        return self._knowledge

    @knowledge.setter
    def knowledge(self, knowledge):
        """Sets the knowledge of this Player.


        :param knowledge: The knowledge of this Player.  # noqa: E501
        :type: Knowledge
        """
        if knowledge is None:
            raise ValueError("Invalid value for `knowledge`, must not be `None`")  # noqa: E501

        self._knowledge = knowledge

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Player, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Player):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
