# coding: utf-8

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StartGame(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'player1': 'str',
        'player2': 'str',
        'options': 'StartGameOptions'
    }

    attribute_map = {
        'player1': 'player1',
        'player2': 'player2',
        'options': 'options'
    }

    def __init__(self, player1=None, player2=None, options=None):  # noqa: E501
        """StartGame - a model defined in Swagger"""  # noqa: E501

        self._player1 = None
        self._player2 = None
        self._options = None
        self.discriminator = None

        self.player1 = player1
        self.player2 = player2
        if options is not None:
            self.options = options

    @property
    def player1(self):
        """Gets the player1 of this StartGame.  # noqa: E501

        Name of player 1  # noqa: E501

        :return: The player1 of this StartGame.  # noqa: E501
        :rtype: str
        """
        return self._player1

    @player1.setter
    def player1(self, player1):
        """Sets the player1 of this StartGame.

        Name of player 1  # noqa: E501

        :param player1: The player1 of this StartGame.  # noqa: E501
        :type: str
        """
        if player1 is None:
            raise ValueError("Invalid value for `player1`, must not be `None`")  # noqa: E501

        self._player1 = player1

    @property
    def player2(self):
        """Gets the player2 of this StartGame.  # noqa: E501

        Name of player 2  # noqa: E501

        :return: The player2 of this StartGame.  # noqa: E501
        :rtype: str
        """
        return self._player2

    @player2.setter
    def player2(self, player2):
        """Sets the player2 of this StartGame.

        Name of player 2  # noqa: E501

        :param player2: The player2 of this StartGame.  # noqa: E501
        :type: str
        """
        if player2 is None:
            raise ValueError("Invalid value for `player2`, must not be `None`")  # noqa: E501

        self._player2 = player2

    @property
    def options(self):
        """Gets the options of this StartGame.  # noqa: E501


        :return: The options of this StartGame.  # noqa: E501
        :rtype: StartGameOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this StartGame.


        :param options: The options of this StartGame.  # noqa: E501
        :type: StartGameOptions
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StartGame, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartGame):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
