# coding: utf-8

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StartGameOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'board_size': 'object'
    }

    attribute_map = {
        'board_size': 'board_size'
    }

    def __init__(self, board_size=None):  # noqa: E501
        """StartGameOptions - a model defined in Swagger"""  # noqa: E501

        self._board_size = None
        self.discriminator = None

        if board_size is not None:
            self.board_size = board_size

    @property
    def board_size(self):
        """Gets the board_size of this StartGameOptions.  # noqa: E501

        Custom board size  # noqa: E501

        :return: The board_size of this StartGameOptions.  # noqa: E501
        :rtype: object
        """
        return self._board_size

    @board_size.setter
    def board_size(self, board_size):
        """Sets the board_size of this StartGameOptions.

        Custom board size  # noqa: E501

        :param board_size: The board_size of this StartGameOptions.  # noqa: E501
        :type: object
        """

        self._board_size = board_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StartGameOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartGameOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
