# coding: utf-8

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_games_game_id_delete(self):
        """Test case for games_game_id_delete

        Delete the given game  # noqa: E501
        """
        pass

    def test_games_game_id_get(self):
        """Test case for games_game_id_get

        Get the current status of a game  # noqa: E501
        """
        pass

    def test_games_game_id_grid_ref_put(self):
        """Test case for games_game_id_grid_ref_put

        Make a move  # noqa: E501
        """
        pass

    def test_games_get(self):
        """Test case for games_get

        Get an index of all known games  # noqa: E501
        """
        pass

    def test_games_post(self):
        """Test case for games_post

        Start a new game  # noqa: E501
        """
        pass

    def test_players_get(self):
        """Test case for players_get

        Get the list of all known players  # noqa: E501
        """
        pass

    def test_players_name_get(self):
        """Test case for players_name_get

        Get information about a specific player  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
