# coding: utf-8

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_player import GetPlayer  # noqa: E501
from swagger_client.rest import ApiException


class TestGetPlayer(unittest.TestCase):
    """GetPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPlayer(self):
        """Test GetPlayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_player.GetPlayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
