# coding: utf-8

# flake8: noqa

"""
    Battleships API

    The API for Battleships  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.get_game import GetGame
from swagger_client.models.get_games_index_response import GetGamesIndexResponse
from swagger_client.models.get_player import GetPlayer
from swagger_client.models.get_players_index_response import GetPlayersIndexResponse
from swagger_client.models.knowledge import Knowledge
from swagger_client.models.move import Move
from swagger_client.models.move_response import MoveResponse
from swagger_client.models.player import Player
from swagger_client.models.ship import Ship
from swagger_client.models.start_game import StartGame
from swagger_client.models.start_game_options import StartGameOptions
from swagger_client.models.start_game_response import StartGameResponse
